export const SIGN_IN='SIGN_IN';
export const SIGN_OUT= 'SIGN_OUT';
export const CREATE_VIDUS = 'CREATE_VIDUS';
export const FETCH_VIDUSS='FETCH_VIDUSS';
export const FETCH_VIDUS='FETCH_VIDUS';
export const DELETE_VIDUS='DELETE_VIDUS';
export const EDIT_VIDUS='EDIT_VIDUS';
export let FETCH_VIDEOS='FETCH_VIDEOS';
export let SELECTED_VIDEO= 'SELECTED_VIDEO';
